import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Providers } from "./provider";
import Navbar from "@repo/ui/Navbar"; 

export const metadata: Metadata = {
  title: "LearnNest",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className="h-full">
        <Providers>
          <Navbar children={children} /> 
        </Providers>
      </body>
    </html>
  );
}
